name: Hexo Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: ./blog
        run: npm install

      - name: Generate Static Files
        working-directory: ./blog
        run: npx hexo generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HEXO_DEPLOY }}
          external_repository: jellybeans-developer/JellyBeansBlogs_Content
          publish_branch: main
          publish_dir: ./blog/public
